services:
  db:
    container_name: postgres
    image: postgres:17.1
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - crs-streams_be

  redis:
    container_name: redis
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - crs-streams_be

volumes:
  db_data:
  redis_data:

networks:
  crs-streams_be:
