services:
  db:
    container_name: postgres
    image: postgres:17.1
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - crs-streams_be

volumes:
  db_data:

networks:
  crs-streams_be:
